### ISSUE TITLE
musl image

### ISSUE THREAD

**Issue by mcandre** [rust-lang/docker-rust#10]
Would be nice to feature a `:musl` tag for building musl Rust binaries!

As an example, see https://github.com/mcandre/docker-linux-rust/blob/master/musl.Dockerfile

**Comment by sfackler** [comment]
This is blocked on official dists targeting musl.

**Comment by shepmaster** [comment]
The playground would also make good use of this :-)

Right now, [we use an unofficial image](https://github.com/integer32llc/rust-playground/blob/master/.travis/compile-backend.sh).

**Comment by mbrubeck** [comment]
https://github.com/japaric/cross has Docker images that include musl toolchains/libraries.

**Comment by vbrandl** [comment]
I would also love to see an official image to link binaries against musl, since they are truly statically linked. Currently I'm using [ekidd/rust-musl-builder](https://hub.docker.com/r/ekidd/rust-musl-builder/) which might be a good base to use.

**Comment by kpcyrd** [comment]
> This is blocked on official dists targeting musl.

Is there a tracking issue that we can link this issue to? :)

**Comment by sfackler** [comment]
I'm not aware of one off the top of my head.

**Comment by ZapAnton** [comment]
rust `1.35` added a [support for the musl distros](https://github.com/rust-lang/rust/pull/58575)
Could it help in resolving this issue?

**Comment by sfackler** [comment]
It looks like rustup doesn't yet publish a musl-based version, so we'd need to get that done first: https://github.com/rust-lang/rustup.rs/issues/1053

**Comment by mati865** [comment]
It's less convenient but you can use tarballs until rustup is fixed: https://forge.rust-lang.org/other-installation-methods.html#standalone

**Comment by DrSensor** [comment]
Seems like https://github.com/rust-lang/rustup.rs/issues/1053 just resolved recently

**Comment by sfackler** [comment]
Great! It appears that a musl build isn't actually published yet, so we may need to wait for the next rustup release.

**Comment by softprops** [comment]
Whats the status on this?

**Comment by mati865** [comment]
There is no change on Rustup situation. It can only be installed using tarballs.

**Comment by DrSensor** [comment]
@sfackler, what is the blocker this time? 🤔

**Comment by sfackler** [comment]
There is no musl build of rustup yet.

**Comment by ZapAnton** [comment]
Rustup was just published 1.19 version with the https://github.com/rust-lang/rustup.rs/pull/1882 resolved
