### ISSUE TITLE
Openssl 3.0.0 - 3.0.6 - Alpine 3.15 vulnerable

### ISSUE THREAD

**Issue by agustik** [rust-lang/docker-rust#119]
What is the status of the rust:1.64-alpine3.15  regarding to the Openssl 3.0.0 - 3.0.6 vulnerabillity?

New version of alpine 3.15.1 was released.
https://alpinelinux.org/posts/Alpine-3.15.1-released.html

https://www.openssl.org/news/secadv/20221101.txt

**Comment by sfackler** [comment]
I believe the docker-library/official-images infrastructure is responsible for rebuilding images.

**Comment by tyranron** [comment]
I guess https://github.com/rust-lang/docker-rust/pull/124 fixes this, as drops support of Alpine 3.15.

**Comment by kpcyrd** [comment]
I also think this can be closed by now.
