### ISSUE TITLE
Update Docker Hub description

### ISSUE THREAD

**Issue by lfrancke** [rust-lang/docker-rust#129]
I don't know if this is a good place to report this.

The description on https://hub.docker.com/_/rust currently says:

```
FROM rust:1.40 as builder
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/myapp /usr/local/bin/myapp
CMD ["myapp"]
```

Can we update this to a newer version?

```
FROM rust:1.66 as builder
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --path .

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/myapp /usr/local/bin/myapp
CMD ["myapp"]
```

I assume lots of people take that snippet, update the Rust version and then _not_ update `buster` to `bullseye`. That's a problem because bullseye is used for later versions of the builder image and buster doesn't have glibc 2.29. So things compiled on one, might not work on the other.

**Comment by kovar** [comment]
Hey Lars 👋 

I believe you can create a pull request [here](https://github.com/docker-library/docs/tree/master/rust) on the `content.md` file according to [these instructions](https://github.com/docker-library/docs#how-do-i-update-an-images-docs).

**Comment by lfrancke** [comment]
Excellent, thank you! I managed not to find that somehow. I'll confirm and will close this issue when I'm done.

**Comment by lfrancke** [comment]
Opened a PR here: https://github.com/docker-library/docs/pull/2275

I'll close this. Sorry for the noise.
