### ISSUE TITLE
Missing linux/amd64 image for 1.67.1* tags on DockerHub

### ISSUE THREAD

**Issue by cailloumajor** [rust-lang/docker-rust#134]
All tags starting with `1.67.1` miss `linux/amd64` images.

See https://registry.hub.docker.com/_/rust/tags

![image](https://user-images.githubusercontent.com/8583146/218053623-23b0b498-4d5e-4b01-8d3c-713bd0b7f3e6.png)

**Comment by cailloumajor** [comment]
Is it related with the failing status of https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/rust/408/

**Comment by sfackler** [comment]
Thanks! Yeah, looks like the Docker folks will have to clean up their builders. We don't have any access to that infrastructure directly unfortunately.

**Comment by cailloumajor** [comment]
It has been fixed: https://github.com/docker-library/official-images/issues/14064#issuecomment-1426267225
