### ISSUE TITLE
1.70: `No such file or directory`

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/docker-rust#148]
Something is wrong with 1.70 version. Switching only the version from `1.69` to `1.70` in my `Dockerfile` causes this error in my final image:

```
bash: ./app: No such file or directory
```

But `./app` obviously is there!

**Comment by frederikhors** [comment]
Maybe related to https://github.com/rust-lang/docker-rust/issues/147#issuecomment-1575433919.

**Comment by tristan-morris** [comment]
This was the problem I had yesterday. My binaries were built against i386 and then running in amd64, which led me to #147. The OP got in there a few minutes before :)

**Comment by ricardoalcantara** [comment]
I had the same problem here, how did you solve it?

**Comment by frederikhors** [comment]
Sorry. I didn't write why I closed it. The cause is: https://github.com/rust-lang/docker-rust/issues/147.

**Comment by ricardoalcantara** [comment]
Oh, they don't have a solution yet. I noticed that the target from the images image 1.69 vs 1.70 are different:

`rust:1.69-bullseye = x86_64-unknown-linux-gnu`
and
`rust:1.70-bullseye = i686-unknown-linux-gnu`

For now I rolled back to 1.69 til they solve that issue.
