### ISSUE TITLE
Create New Debian Testing (trixie) Images

### ISSUE THREAD

**Issue by dvn0** [rust-lang/docker-rust#152]
With the release of Debian Bookworm as the new stable, Debian Trixie is the new `testing`. Therefore, it would be nice to have a Rust image based on Debian Trixie.

**Comment by sfackler** [comment]
Updated in 3c948e6255412b0b72ef4c4b1a4cee448bed4c29. It'll get picked up in for 1.72.0.

**Comment by dvn0** [comment]
Thanks!
