### ISSUE TITLE
I think we have another issue with 1.72.

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/docker-rust#155]
I think we have another https://github.com/rust-lang/docker-rust/issues/147 issue with 1.72.

**Comment by frederikhors** [comment]
I can confirm with 1.71 it works.

With 1.72 I have this error:

```
error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

I'm using Dockerfile:

```Dockerfile
FROM amd64/rust:1.72
...
```

Same for 1.71 (which works).

**Comment by sfackler** [comment]
No, that means that OpenSSL libraries are not installed in your new image. The default base was moved to Debian Bookworm which may have changed whatever libraries are installed by default.
