### ISSUE TITLE
When is the image rebuilt?

### ISSUE THREAD

**Issue by harryzcy** [rust-lang/docker-rust#172]
It seems that images are build multiple times for the same rust version. 
i.e. `1.75.0-bookworm` changed from `sha256:ea9465364458a5948adb50e2a0636021e5e40a5e5135e720481522e7f456346e` to `sha256:1c5eaf3e66465de5cdd71f66b0ada48cec56d9c267f67880785fb6a29085c444` yesterday.

What causes these images to be rebuild? Are there anything changed? Can you document this?

**Comment by sfackler** [comment]
Image builds are handled by Docker's official image infrastructure. I can't speak to why they rebuild, but I could imagine it was due to an update to the base image.
