### ISSUE TITLE
i386/rust:1.75.0 fails on Gitlab CI

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/docker-rust#173]
On Gitlab CI, for the following `.gitlab-ci.yml`:
```yml
i386-version-1:
  image: i386/rust:1
  stage: test
  script:
  - echo Fine

i386-version-1.74.1:
  image: i386/rust:1.74.1
  stage: test
  script:
  - echo Fine

i386-version-1.75.0:
  image: i386/rust:1.75.0
  stage: test
  script:
  - echo Fine
```

i386/rust:1.74.1 works fine, but i386/rust:1.75.0 and i386/rust:1 (which presumably is the same as 1.75.0) fail with an error message that looks like:
```
Running with gitlab-runner 16.6.0~beta.105.gd2263193 (d2263193)
  on blue-1.saas-linux-small.runners-manager.gitlab.com/default j1aLDqxS, system ID: s_ccdc2f364be8
  feature flags: FF_USE_IMPROVED_URL_MASKING:true
Preparing the "docker+machine" executor 00:04
Using Docker executor with image i386/rust:1 ...
Pulling docker image i386/rust:1 ...
WARNING: Failed to pull image with policy "always": no matching manifest for linux/amd64 in the manifest list entries (manager.go:237:0s)
ERROR: Job failed: failed to pull image "i386/rust:1" with specified policies [always]: no matching manifest for linux/amd64 in the manifest list entries (manager.go:237:0s)
```

This can be seen in [this Gitlab pipeline](https://gitlab.com/tspiteri/test-ci/-/pipelines/1141631771).

**Comment by Muscraft** [comment]
I spent some time looking into this and genuinely can't tell why that is happening. I  ran `docker pull i386/rust:1.75.0` locally, and it worked. If you rerun the CI jobs, does it still fail? I see [that some image tags](https://hub.docker.com/_/rust/tags) were pushed less than an hour ago; maybe that fixed it?

**Comment by tspiteri** [comment]
I just reran the failed `rust:1` and `rust:1.75.0` tests and they failed again.

**Comment by tspiteri** [comment]
This seems to have been resolved: I cannot reproduce the issue any more. Maybe it was a quirk in GitLab/something else which has now been resolved.
