### ISSUE TITLE
Missing apt sources

### ISSUE THREAD

**Issue by dipk-mish7** [rust-lang/docker-rust#181]
I tried to write a dockerfile using 1.76.0 and found that this image has no longer /etc/apt/sources.list, This is present in 1.70.0 image.. Could u please let me know if this is expected?
I was using rust 1.70.0 image in my dockerfile as base image for svix.
This had /etc/apt/sources.list file in it and I was updating my jfrog artifactory packages in it.. but for some reasons 1.76.0 version of docker image of rust do not have this..

I posted it here too https://github.com/rust-lang/docker-rust/issues/182

**Comment by dipk-mish7** [comment]
yes.. I can only see /etc/apt/sources.list.d but not sure where should I add my dependency of artifactory.

**Comment by sfackler** [comment]
What does Google say about adding sources to /etc/apt/sources.list.d?

**Comment by dipk-mish7** [comment]
Couldn't get anything on google related to this  but I did tried to add it here `/etc/apt/sources.list.d` however it gave me below error @sfackler 
![image](https://github.com/rust-lang/docker-rust/assets/52923075/2ede3c24-4986-47a4-a215-7187c9062844)

**Comment by sfackler** [comment]
/etc/apt/sources.list.d is supposed to be a directory of files, not a file.

https://stackoverflow.com/questions/26020917/what-is-the-function-of-etc-apt-sources-list-d
