### ISSUE TITLE
Missing apt sources

### ISSUE THREAD

**Issue by dipk-mish7** [rust-lang/docker-rust#182]
I tried to write a dockerfile using 1.76.0 and found that this image has no longer /etc/apt/sources.list, This is present in 1.70.0 image.. Could u please let me know if this is expected?
I was using rust 1.70.0 image in my dockerfile as base image for svix.
This had /etc/apt/sources.list file in it and I was updating my jfrog artifactory packages in it.. but for some reasons 1.76.0 version of docker image of rust do not have this..

**Comment by Muscraft** [comment]
closing in favor of #181
