### ISSUE TITLE
Alpine images has no layers built

### ISSUE THREAD

**Issue by toast-ts** [rust-lang/docker-rust#190]
Hi, I'm not sure if this is right place but I'll just leave it here and be corrected later on.
But, on Docker Hub registry, it seems that the Alpine images aren't published properly and there's no layers if I go to view the page. Keep in mind that Bookworm and others do have layers as seen below;

![image](https://github.com/rust-lang/docker-rust/assets/96593068/27a51e58-6f19-48ec-8e5f-9e54024e2a49)

No layers if I were to explore the image here:
https://hub.docker.com/layers/library/rust/1.77-alpine3.19/images/sha256-eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb?context=explore

And to top it off, I came here to report the issue because my Gitea workflow did not pick up Rust 1.77 from Docker registry as seen here:

![image](https://github.com/rust-lang/docker-rust/assets/96593068/7017939b-0763-4e4d-a31f-d0d52a183e5c)

**Comment by sfackler** [comment]
The images are built in the Docker hub official image infrastructure - you'll probably just have to wait until they work through whatever backlog they have currently.

**Comment by toast-ts** [comment]
Okay got it, seems that the Alpine images now has layers, I'll close this now.
