### ISSUE TITLE
Missing tags for `1.77.1` images

### ISSUE THREAD

**Issue by fenollp** [rust-lang/docker-rust#193]
```shell
0 0s  λ docker pull rust:1.77.0-slim
1.77.0-slim: Pulling from library/rust
Digest: sha256:e785e4aa81f87bc1ee02fa2026ffbc491e0410bdaf6652cea74884373f452664
Status: Image is up to date for rust:1.77.0-slim
docker.io/library/rust:1.77.0-slim

0 1s  λ docker pull rust:1.77-slim
1.77-slim: Pulling from library/rust
Digest: sha256:e785e4aa81f87bc1ee02fa2026ffbc491e0410bdaf6652cea74884373f452664
Status: Image is up to date for rust:1.77-slim
docker.io/library/rust:1.77-slim

0 2s  λ docker pull rust:1.77.1-slim
Error response from daemon: manifest for rust:1.77.1-slim not found: manifest unknown: manifest unknown
1 2s  λ 
```

It's not just me: github actions runners have the same failure :)

**Comment by Muscraft** [comment]
Quoting @sfackler in [#190](https://github.com/rust-lang/docker-rust/issues/190#issuecomment-2014105427)
> The images are built in the Docker hub official image infrastructure - you'll probably just have to wait until they work through whatever backlog they have currently.

In this case, the official image builder has not yet built and pushed the new images. It can take hours after things are updated in the official images repo for the new images to get built and published. I would check the [rust tag](https://registry.hub.docker.com/_/rust/tags) in a few hours (or tomorrow) to see if `rust:1.77.1-slim` has been published.
