### ISSUE TITLE
Edition 2018 programs not compiling

### ISSUE THREAD

**Issue by andradei** [rust-lang/docker-rust#38]
When running `cargo build | check` inside a container based with this image, the crates get downloaded but don't compile. This is the error I get:

```
    (Omitting big list of crates being downloaded and checked)

    Checking trust-dns-resolver v0.10.0
    Checking actix v0.7.8
    Checking hyper-tls v0.3.1
    Checking reqwest v0.9.5
    Checking actix-net v0.2.4
    Checking sparkpost v0.4.1
    Checking actix-web v0.7.15
    Checking simple-auth-server v0.1.0 (/app)
error: Edition 2018 is unstable and only available for nightly builds of rustc.

error: Could not compile `my-rust-program`.

To learn more, run the command again with --verbose.
```

**Comment by andradei** [comment]
Also the Rust toolchain that is being used isn't 1.31.0, but `1.30.1-x86_64-unknown-linux-gnu (default)`

**Comment by andradei** [comment]
The work-around I found is to run the following in the container or put it in my Dockerfile:

```
    rustup self update \
    && rustup toolchain uninstall stable \
    && rustup toolchain install stable \
    && rustup default stable
```

**Comment by sfackler** [comment]
Are you sure you're using the 1.31 image?

**Comment by andradei** [comment]
> Are you sure you're using the 1.31 image?

Yes. But I'll remove the image and pull it again just to be sure. Have you checked the `rustup` version? There was a bug in the toolchain of the newest version that was fixed after 1.31.0 was released.

**Comment by sfackler** [comment]
The version of rustc on the 1.31.0 image is 1.31.0.

**Comment by andradei** [comment]
Let me highlight that I am talking about `rustup`, not `rustc`.

**Comment by sfackler** [comment]
That is not the problem.

**Comment by jthelin** [comment]
If `rustup` v1.16.0 is needed for 2018 code, then the problem is in the `Dockerfile`, which is still using v1.15.0 of rustup-init

https://github.com/rust-lang/docker-rust/blob/e7703b2cf525f2525bdf8d131cd66b5b38b1513c/1.31.0/stretch/Dockerfile#L17

```
$ docker run --rm -it rust:latest bash -c "rustc --version ; cargo --version ; rustup --version"
rustc 1.31.0 (abe02cefd 2018-12-04)
cargo 1.31.0 (339d9f9c8 2018-11-16)
rustup 1.15.0 (f0a3d9a84 2018-11-27)
```

**Comment by sfackler** [comment]
Rustup 1.16.0 is not needed for 2018 code.

**Comment by andradei** [comment]
@sfackler You're right. The issue might have been just timing. Unfortunately, I can't find where I read the toolchain had to be updated shortly after Rust 2018 was released in order for this problem to go away.

I wrongly assumed rustup 1.15.0 was the problem, but 1.16.0 didn't change any of its behavior. Sorry about that.

For now, everything is working.
