### ISSUE TITLE
Why no caching? All dependencies are re-compiled every time.

### ISSUE THREAD

**Issue by dessalines** [rust-lang/docker-rust#40]
I found that upon every run of my `docker-compose build`, this was by default not caching any of the dependencies, and rebuilding them all from scratch, which would take ~10 minutes per build.

I found this  [elaborate guide](http://whitfin.io/speeding-up-rust-docker-builds/) or how to cache dependencies for anyone interested, but it seems like both of the features listed in there: caching the dependencies, and optimizing the image size, should be part of this docker already. They managed to cut the build time by 90%, and build size by 95%.

**Comment by kpcyrd** [comment]
There is no way to do it in this image. These steps have to be done by the project building on top of the base image.

Note that you can further reduce the size by using `debian:stretch` instead of `rust` for the second stage.

**Comment by sfackler** [comment]
If you have specific suggestions on changes to the Dockerfiles, I'd be interested in hearing them, but "make caching work" is not really actionable.

**Comment by dessalines** [comment]
Maybe just linking to the guide I posted in the docker readme, since cargo doesn't yet have a `--build-dependencies` option.
