### ISSUE TITLE
Images with default profile

### ISSUE THREAD

**Issue by dmarcoux** [rust-lang/docker-rust#48]
Hey,

I use the official Docker image in a development environment and having an image with the default profile of `rustup` would be quite handy. So this would mean building images with `rustup-init --profile default`.

**Comment by sfackler** [comment]
Can't you just `rustup component add rust-docs` if you need them?

**Comment by dmarcoux** [comment]
It's an option for sure and I do it for now, but I would prefer to pull a Docker image which already contains the default profile.

Should I close the issue? I sent a PR in case you consider adding this.

**Comment by sfackler** [comment]
I don't really want to have a huge profusion of image types. You could make your own image based off of the official one that pulls in docs though.

**Comment by dmarcoux** [comment]
Alright, no worries! Thank you for your quick replies. Have a good day.
