### ISSUE TITLE
Provide Alpine images for ARM

### ISSUE THREAD

**Issue by amyspark** [rust-lang/docker-rust#50]
Hey,

I've just ran into a separate issue when trying to set up CI for my little project (https://github.com/rust-lang/cargo/issues/7563).
I wanted to try other alternatives on my Raspberry Pi 4, but I noticed that [Alpine-based images are provided only for x64](https://hub.docker.com/_/rust?tab=tags&page=1&name=alpine).

Would it be possible to add ARM platforms to the list as well?

**Comment by sfackler** [comment]
We'd first need a rustup distribution for your target, and currently the only MUSL-based one is x86_64.

**Comment by sfackler** [comment]
That means that there is a Rust toolchain for ARM musl. There is not a rustup binary for ARM msul, though: https://rust-lang.github.io/rustup/installation/other.html

**Comment by tcurdt** [comment]
@sfackler Thanks for clarifying! Are you aware of an open issue for that in `rustup` land?

**Comment by sfackler** [comment]
Not off the top of my head. You could check their github.

**Comment by tcurdt** [comment]
This seems related https://github.com/rust-lang/rustup/issues/2003

**Comment by tcurdt** [comment]
@sfackler I am a little unsure on the path forward. IIUC the only reason why there is no rustup binary for ARM (which is required for alpine arm images), is because there are not enough build minutes?

**Comment by sfackler** [comment]
I am not involved in rustup - you should ask them.

**Comment by tcurdt** [comment]
Alright, I asked on the `rustup` issue.
