### ISSUE TITLE
Install gcc-arm-linux-gnueabihf and binutils-arm-linux-gnueabihf for arm builds requiring C packages

### ISSUE THREAD

**Issue by Lindenk** [rust-lang/docker-rust#53]
Although it isn't the highest priority, building an arm package using C bindings takes several extra minutes because `gcc-arm-linux-gnueabihf` and `binutils-arm-linux-gnueabihf`need to be installed first.

The fix would be to add `gcc-arm-linux-gnueabihf` and `binutils-arm-linux-gnueabihf` to the list of installed packages for the image.

**Comment by sfackler** [comment]
These are based off of the buildpack-deps image. You should file this request there if you think it should be included in standard official Docker images.
