### ISSUE TITLE
OpenSSL when cross-compiling for musl

### ISSUE THREAD

**Issue by arlyon** [rust-lang/docker-rust#58]
This is a continuation of #11

Rust is no longer able to find the OpenSSL headers [as early as July 2019](https://github.com/rust-lang/docker-rust/issues/11#issuecomment-508296169) on the latest tag (`1.42.0-buster`) despite them being there:

```
➜ docker run --rm rust:latest head /usr/include/openssl/opensslv.h
/*
 * Copyright 1999-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_OPENSSLV_H
```

According to [this issue](https://github.com/sfackler/rust-openssl/issues/603) trying to get rust to know where all the headers are is a pain point.

**Comment by sfackler** [comment]
If you are cross compiling, you need a copy of OpenSSL built for the target. The image's OpenSSL is linked to glibc, not musl libc.
