### ISSUE TITLE
Please add stable / beta / nightly tags

### ISSUE THREAD

**Issue by jplatte** [rust-lang/docker-rust#60]
Currently, there's only images for specific versions, and `latest`, whatever that means. Having `stable`, `beta` and `nightly` tags would be very useful for Docker-based CI.

**Comment by sfackler** [comment]
`latest` is equivalent to `stable`. Beta images are tracked by #14, and nightly images are provided on the `rustlang/rust` image.

**Comment by jplatte** [comment]
Thanks for the clarification.
