### ISSUE TITLE
Add musl-dev to alpine images

### ISSUE THREAD

**Issue by mamins1376** [rust-lang/docker-rust#68]
Currently when building something that involves compiling C (`bat` as an example), at the linking stage the following happens, due to missing `/usr/lib/crti.o`:
```
   ...
   Compiling clap v2.33.3
   Compiling chrono v0.4.19
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" ...  "-Wl,-Bdynamic" "-lgcc_s" "-lc"
  = note: /usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
          collect2: error: ld returned 1 exit status

error: aborting due to previous error
```

This can be eliminated simply by adding `musl-dev` after [RUN apk add ...](https://github.com/rust-lang/docker-rust/blob/0ffafaf3da2851f4c41c70f7dd184eb3d144fab6/Dockerfile-alpine.template#L5).

**Comment by sfackler** [comment]
The official alpine images tend to be as small as possible - take go's for example: https://hub.docker.com/_/golang which doesn't even include gcc.

**Comment by mamins1376** [comment]
What's the point of including gcc when there are not even std headers? Is it a common scenario to compile `no_std`-equivalent C/C++ code?

**Comment by sfackler** [comment]
rustc uses gcc as its linker.

**Comment by mamins1376** [comment]
Ok, got it. I guess `RUN apk add --no-cache musl-dev` should always be the first line of some Dockerfiles.
Not a big deal though, the trade-off seems appropriate. Thanks for your response.

**Comment by wrenix** [comment]
Why is that not default in the rust-alpine container preinstalled?

**Comment by polarathene** [comment]
Given the discussion at https://github.com/rust-lang/compiler-team/issues/422

Should that change land, the user will fail to build a simple "hello world" program when dynamic linking becomes default with musl targets.

They'd either need to know to specify `-C link-self-contained=yes` as a rust flag for cargo (_additionally  with `-C target-feature=+crt-static` if they want to get static builds back_), or to install `musl-dev` in the container.

[Documenting that on DockerHub](https://hub.docker.com/_/rust) would be the better route if the alpine image is meant to prioritize size over UX (_less of an issue until the image toolchain defaults to dynamic linking_), but only if the size increase was notable..

---

## `musl-dev` adds 11MB uncompressed to the existing 825MB image (`1.33%` image weight increase)

```Dockerfile
FROM rust:alpine
RUN apk add --no-cache musl-dev
```

```console
$ docker build -t rust-musl-dev .

# Barely an increase:
$ docker images
REPOSITORY            TAG       IMAGE ID       CREATED         SIZE
rust-musl-dev         latest    0ae623d62975   7 seconds ago   836MB
rust                  alpine    5d20fa327476   2 days ago      825MB
rust                  latest    890a6b209e1c   2 weeks ago     1.5GB
golang                alpine    bb520cee46ae   11 days ago     222MB
golang                latest    4c88d2e04e7d   11 days ago     815MB

$ docker image history rust-musl-dev
IMAGE          CREATED         CREATED BY                                      SIZE      COMMENT
0ae623d62975   2 minutes ago   RUN /bin/sh -c apk add --no-cache musl-dev #…   10.3MB    buildkit.dockerfile.v0
<missing>      2 days ago      /bin/sh -c set -eux;     apkArch="$(apk --pr…   680MB
<missing>      2 days ago      /bin/sh -c #(nop)  ENV RUSTUP_HOME=/usr/loca…   0B
<missing>      4 weeks ago     /bin/sh -c apk add --no-cache         ca-cer…   138MB
<missing>      7 weeks ago     /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B
<missing>      7 weeks ago     /bin/sh -c #(nop) ADD file:756183bba9c7f4593…   7.34MB
```

Here are those two layers 680MB + 138MB (via `dive`):

![image](https://github.com/rust-lang/docker-rust/assets/5098581/e6ca3e41-8d1e-4645-a65f-1df6d957a398)

![image](https://github.com/rust-lang/docker-rust/assets/5098581/1e7b5473-bff1-41a7-b6eb-13c383465b19)

The small addition of `musl-dev` for improved UX:

![image](https://github.com/rust-lang/docker-rust/assets/5098581/022eb664-5d09-4f05-ba90-d226ebbff2c0)

We're looking at a modest 1.33% increase in image weight, not a deal breaker.

**Comment by EvanCarroll** [comment]
@mamins1376 I agree with @polarathene here. Having images that are currently _useless_ at compiling any modern Rust project in order to save 1.33% on a build image seems highly awkward. Let's say Rust does enable dynamic linking on musl? So what, we save 1.33% in that case? And if you want to compile static (which is a huge gain if you want to deploy using scratch/distroless) then you'll still get value out of this anyway.

I don't understand the merit here.

The Alpine image to isn't supposed to prioritize size. It's supposed to prioritize building for the musl target which right now is static. And lastly, let's take assume we want Alpine to prioritize size, can't we take the interest in this issue as evidence that people want another target for rust to prioritize static compilation? Speak for my own use case, I don't care about Alpine. I just want to build for a scratch image.

**Comment by polarathene** [comment]
> While `link-self-contained` doesn't work with `musl`

Just to clarify for readers here regarding that referenced issue, see [this table](https://github.com/rust-lang/rust/issues/149371#issuecomment-3595000457) that better explains what issue happened and why.

`link-self-contained=yes` is rather specific to the musl target in this case that you'd usually have as a default (_unsupported by Alpine's own `cargo` package that dynamic links by default_), and when you opt-out of the static linking default with `-C target-feature=-crt-static` you should also set `-C link-self-contained=no` (_or use an explicit `--target` option with `cargo build`, as is required when doing `-C target-feature=+crt-static` when proc-macro may be involved during builds_).
