### ISSUE TITLE
Should we add alpine-sdk in this image?

### ISSUE THREAD

**Issue by ulwlu** [rust-lang/docker-rust#73]
Proposal:
- Add alpine sdk in images

Reason:
- This image commonly faces error with `linking with "cc" failed: exit code: 1`.
- ref: https://github.com/rust-lang/rust/issues/25289
- ref: https://github.com/gliderlabs/docker-alpine/issues/294
- Not a few dependencies requires this toolchain such as proc_macro, so I think this proposal helps many people.

As approved, I will send PR.

**Comment by jbg** [comment]
Would be better to include `build-base`; `alpine-sdk` contains a bunch of other things for making Alpine releases that don't really need to be in an image like this.

**Comment by ulwlu** [comment]
I see.
