### ISSUE TITLE
Publish/mirror to ECR public gallery

### ISSUE THREAD

**Issue by Fuuzetsu** [rust-lang/docker-rust#75]
At the end of 2020, AWS [released public container registry](http://gitlab.tsuru.it/tsuru/engine/-/issues/590). This was largely motivated by the Docker Hub limits put it place recently.

There are some [existing mirrors](https://gallery.ecr.aws/?searchTerm=rust) in the ECR public gallery but they all come from individuals. Therefore, we either have to trust that images haven't been tampered with or mirror the images ourselves.

It'd be great if the official images would be posted via official, verified account in the ECR public gallery. This allows AWS users to not worry about Docker Hub and be confident in the images being provided.

**Comment by yosifkit** [comment]
Good news, Docker Inc. mirrors all of the Official Images automatically: https://gallery.ecr.aws/docker/. See also the [Docker Blog post](https://www.docker.com/blog/news-from-aws-reinvent-docker-official-images-on-amazon-ecr-public/).

**Comment by Fuuzetsu** [comment]
Thanks for the notice, I didn't know this. I now switched to using the official Rust image mirror rather than using a private ECR mirror like we were so far.

Thanks!
