### ISSUE TITLE
version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by DoubleCouponDay** [rust-lang/docker-rust#77]
I am basing my dockerfile on the `rust` base image.
When deploying my image to an azure container, I receive this log:
```./bot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./bot)```

./bot is my application.
The error also occurs when I perform `docker run` on my Linux Mint desktop.

How can I get GLIBC into my container?

**Comment by DoubleCouponDay** [comment]
I need to build my program inside the rust container so that the matching GLIBC version is used.

**Comment by DoubleCouponDay** [comment]
Fixed by building the application in the container instead of in my local environment.

**Comment by Faroukhamadi** [comment]
> Fixed by building the application in the container instead of in my local environment.

Encountered the same problem, can you share what you changed in the Dockerfile ?

**Comment by dnettoRaw** [comment]
same probleme here

**Comment by dnettoRaw** [comment]
> > Fixed by building the application in the container instead of in my local environment.
> 
> Encountered the same problem, can you share what you changed in the Dockerfile ?

founded just change
`FROM debian:buster-slim`
to
`FROM  debian:bullseye`

https://github.com/rust-lang/docker-rust/issues/105#issuecomment-1149081766
