### ISSUE TITLE
i386 Alpine Docker build

### ISSUE THREAD

**Issue by ernestask** [rust-lang/docker-rust#81]
Hi,

Is there any technical reason why there isn’t an i386 build for the Alpine images?

There is i386/alpine that seems perfectly usable *and* there are i386 Debian builds, so I’m left scratching my head here.

**Comment by sfackler** [comment]
It doesn't exist because no one has asked for it. PRs welcomed.

**Comment by ernestask** [comment]
Well, today is your lucky day!

**Comment by ernestask** [comment]
Refer to the PR for issues with this.
