### ISSUE TITLE
`GLIBC_2.29' not found

### ISSUE THREAD

**Issue by 51yu** [rust-lang/docker-rust#89]
I was using the recommended dockerfile to build image and run app, all looks good, till upgrade 
builder image from `1.54` to `1.56` ...
```
FROM rust:1.56 as builder
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/myapp /usr/local/bin/myapp
CMD ["myapp"]
```
run into 
```
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by myapp)
```

**Comment by sfackler** [comment]
The default tag of 1.56 is now built off of Debian Bullseye which ships a newer glibc. You should upgrade your second base image to `debian:bullseye-slim`.
