### ISSUE TITLE
Missing linux/amd64 in 1.57 images

### ISSUE THREAD

**Issue by hzuo** [rust-lang/docker-rust#92]
```shell
❯ docker pull rust:1.57.0-buster
1.57.0-buster: Pulling from library/rust
no matching manifest for linux/amd64 in the manifest list entries
```

Most of the 1.57 images only have `linux/386` and `linux/arm64/v8` variants:
https://hub.docker.com/_/rust?tab=tags

**Comment by sfackler** [comment]
https://github.com/docker-library/official-images/pull/11441#issuecomment-985814851

**Comment by hzuo** [comment]
Looks like they've worked through the queue
